netmanager_web/pages/views.py
# -*- coding: utf-8 -*-
from flask import Blueprint, render_template
from flask import current_app, jsonify, request, flash, redirect, url_for
from . import Pagination, crossdomain

import sys

import pprint
import datetime
from collections import namedtuple

from pytz import timezone

from .snow import SnowForm
from .device import AddDeviceConfigurationForm, DeviceForm, AddDeviceForm
from .helpers.rest import get_url, get_rest_command, select_keys, get_sites, get_site, get_vlans, get_devices, get_info
from .site import SearchSiteForm, AddSiteForm
from .router import RouterConfigForm

import json
import requests
import wtforms_json
from flask import request

requests.packages.urllib3.disable_warnings()

PER_PAGE = 15

DateInterval = namedtuple('DateInterval', 'value description range')

DATE_INTERVALS = [
    DateInterval(value='today',      description='Today',            range={"gt": "now-1d/d",  "lte": "now/d"}),
    DateInterval(value='thisweek',   description='Previous 7 days',  range={"gt": "now-7d/d",  "lte": "now"}),
    DateInterval(value='thismonth',  description='Previous 30 days', range={"gt": "now-30d/d", "lte": "now"}),
    DateInterval(value='tomorrow',   description='Tomorrow',         range={"gte": "now",      "lte": "now+1d/d"}),
    DateInterval(value='nextweek',   description='Next 7 days',      range={"gte": "now",      "lte": "now+7d/d"}),
    DateInterval(value='everything', description='Everything',       range=None),
]

pages_app = Blueprint('pages_app', __name__)

@pages_app.route('/hello')
def index():
    return render_template('pages/index.html')

@pages_app.route('/about')
def about():
    return render_template('pages/about.html')


@pages_app.route('/cost')
def cost():
    return render_template('pages/cost.html')


@pages_app.route('/find', methods=['POST'])
def boxsearch():
    data = request.form
    pprint.pprint(data)
    return render_template('pages/element.html')


@pages_app.route('/snow', methods=('GET', 'POST'))
def snow():
    form = SnowForm()
    form.validate_on_submit()
    if form.is_submitted():
        site_name = request.form.get('site_name')
        payload = select_keys(request.form, ['category', 'delete_if_exists', 'kbps'])
        r = requests.post(current_app.config['API_ENDPOINT'] + '_snow/{}'.format(site_name), data=payload, verify=False)
        print(current_app.config['API_ENDPOINT'] + '_snow/{}'.format(site_name))
        if r.status_code == 200:
            flash("{} - {}".format(r.status_code, '{} created'.format(site_name)), 'info')
        else:
            flash("{} - {}".format(r.status_code, r.text), 'error')
        return render_template('pages/snow.html', form=form)
    return render_template('pages/snow.html', form=form)


@pages_app.route('/add-site', methods=('GET', 'POST'))
def add_site():
    form = AddSiteForm()
    form.validate_on_submit()
    if form.is_submitted():
        site_name = request.form.get('site_name')
        payload = select_keys(request.form, ['users', 'ipphones'])
        #headers = {'Content-Type': 'application/x-www-form-urlencoded', 'Accept': 'application/json'}
        r = requests.post(current_app.config['API_ENDPOINT'] + 'sites/{}'.format(site_name), data=payload, verify=False)
        print(current_app.config['API_ENDPOINT'] + 'sites/{}'.format(site_name))
        print(payload)
        print(r.status_code)
        if r.status_code == 200:
            flash("{} - {}".format(r.status_code, '{} created'.format(site_name)), 'info')
            return render_template('pages/site.html', data=json.loads(r.text))
        else:
            flash("{} - {}".format(r.status_code, json.loads(r.text)['message']), 'error')
        print('wahappa')
        return render_template('pages/site-add.html', form=form)
    return render_template('pages/site-add.html', form=form)



# this route is not needed, addition of a device will work anyway
@pages_app.route('/device', methods=('GET', 'POST'))
def device():
    form = DeviceForm()
    form.validate_on_submit()
    if form.is_submitted():
        return render_template('pages/device.html', form=form)
    return render_template('pages/device.html', form=form)


@pages_app.route('/', methods=('GET', 'POST'))
@pages_app.route('/site', methods=('GET', 'POST'))
def site():
    form = SearchSiteForm(request.values)
    form.validate_on_submit()

    print(request.method)
    print(request.form)

    if form.is_submitted():
        if 'submit_add_device' in request.form:
            print("Got a submit event on the AddDevice form")
            submitted = request.form.to_dict(flat=True)
            submitted.pop('csrf_token', None)
            print("SUBMITTED DEVICE", submitted)
            add_device = DeviceForm(site_name=submitted['site_name'], dev_cfg=submitted['dev_cfg'])
            add_device.site_name.render_kw = {'readonly': True}
            add_device.dev_cfg.render_kw = {'readonly': True}
            add_device.dev_cfg.description = '' # just to remove the description
            return render_template('pages/device.html', form=add_device)

        if 'submit_device' in request.form:
            print("Got a submit event on the Device form")
            submitted = request.form.to_dict(flat=True)
            submitted.pop('csrf_token', None)
            # submitted['site'] = submitted.pop('site_name')
            # submitted['site_name'] = submitted['site']
            # submitted['auto_connect'] = submitted.get('auto_connect', 'false').replace('y', 'true')
            if submitted.get('auto_connect'):
                submitted['auto_connect'] = submitted.get('auto_connect').replace('y', 'true')
            # submitted.pop('stack_partner', None)
            submitted.pop('submit_device', None)
            # TODO: actually insert 'submitted' into a database somewhere
            # i.e. call the rest endpoint
            print("CALL post_url with {}".format(submitted))
            # CALL post_url with {'dev_cfg': 'string3', 'building': 'HB2', 'df': 'M01', 'serial': '15135424',
            #                     'stack_partner': '123', 'wan_line': 'adsga', 'site': 'DKAARHED42',
            #                     'auto_connect': 'false'}
            r = requests.post(current_app.config['API_ENDPOINT'] + 'devices', data=submitted, verify=False)
            print('post_url responds with: ')
            print(r.text)
            if r.status_code == 500:
                flash("{} - {}".format(r.status_code, r.text), 'info')
            # if r.status_code != 200:
            #    add_device = AddDeviceForm(request.values)
            #    return render_template('device.html', form=add_device)
            submitted['site'] = submitted.pop('site_name')
            if r.status_code == 200:
                flash('{} was added added to {} - {}'.format(submitted['dev_cfg'], submitted['site'], submitted['df']), 'info')

        if ('submit_search_site' in request.form and bool(form.site_name.data)) or 'submit_device' in request.form:
            # DATA FOR THE "SHOW SITE INFORMATION" Page
            #
            data = get_site(form.site_name.data)
            vlans = None
            devices = None
            add_device = None

            if bool(data):
                vlans = get_vlans(form.site_name.data)
                devices = get_devices(form.site_name.data)
                add_device = AddDeviceForm(request.values)
                if bool(data.get('device_configurations')):
                    print(data['device_configurations'])
                    choices = [(device['name'], device['name']) for device in data['device_configurations']]
                    add_device.dev_cfg.choices = choices

            return render_template('pages/site-search.html', form=form, vlans=vlans, devices=devices, data=data, add_device=add_device)
        return render_template('pages/site-search.html', form=form)
    return render_template('pages/site-search.html', form=form)


@pages_app.route('/sites', methods=('GET', 'POST'))
def sites():
    data = get_sites()
    print(data)
    return render_template('pages/sites.html', sites=data)


@pages_app.route('/configure', methods=('GET', 'POST'))
def configure():
    form = RouterConfigForm()
    form.validate_on_submit()  # to get error messages to the browser
    print("configuring%s+%s" % (form.router.data, form.switch.data) + " with SNOW ID: %s " % (form.snow.data) + " %s APs" % (form.aps.data))

    if form.is_submitted():
        url = current_app.config['API_ENDPOINT'] + "sites"
        r = requests.get(url)
        print(r.text)
        # a form that is able to show the information will need to be made
        return render_template('pages/configuring.html', form=form)

    return render_template('pages/configure.html', form=form)


def _from_utc(utcTime, fmt="%Y-%m-%dT%H:%M:%S.%fZ"):
    """
    Convert UTC time string to time.struct_time
    """
    utcdatetime = datetime.datetime.strptime(utcTime, fmt)
    localdatetime = timezone(current_app.config['ADE_TIMEZONE']).fromutc(utcdatetime)
    return localdatetime

netmanager_web/templates/base.html
{% import "bootstrap/wtf.html" as wtf %}
{% import "bootstrap/fixes.html" as fixes %}
{% import "bootstrap/utils.html" as util %}

<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="../../../../favicon.ico">

  <title>{% block title %}Remember to set the title{% endblock %}</title>

  <!-- Bootstrap core CSS -->
  <link href="{{ url_for('static', filename='bootstrap.min.css') }}" rel="stylesheet">

  <!-- Font Awsome CSS -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">

  <!-- Custom styles for this template -->
  <link href="{{ url_for('static', filename='dashboard.css') }}" rel="stylesheet">

  <!-- Typeahead CSS -->
  <link href="{{ url_for('static', filename='typeaheadjs.css') }}" rel="stylesheet">

  <!-- Animate CSS -->
  <link href="{{ url_for('static', filename='animate.css') }}" rel="stylesheet">

  <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
  <script src="{{ url_for('static', filename='html5shiv.min.js') }}"></script>
  <![endif]-->
  {% block extrahead %}{% endblock %}

  <style>
span.twitter-typeahead .tt-input {
  color: #fff;
  background-color: rgba(255, 255, 255, .1);
  border-color: rgba(255, 255, 255, .1);
}
  </style>

</head>

<body>

<nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">Netmanager</a>
  <!--https://dev-netsoa.vestas.net/netmanager/1.0.0/sites/DKCLP?list_viable_devices=true
    https://github.com/twitter/typeahead.js/issues/378
    https://github.com/twitter/typeahead.js/issues/411
  -->
  <!-- <form action="{{ url_for('pages_app.boxsearch') }}" method="post"> -->
  <!-- <div id="boxsearch"> -->
      <input class="form-control form-control-dark w-100 twitter-typeahead" type="text" placeholder="Search" aria-label="Search">
  <!-- </div> -->
  <!-- </form> -->
  <ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap">
      <a class="nav-link" href="#">Sign out</a>
    </li>
  </ul>
</nav>

<div class="container-fluid">
  <div class="row">
    {% block leftnavigation %}
    {{nav.left.render("bootstrap_dashboard_renderer")}}
    {% endblock %}
    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
        {% block content %}
        {% endblock %}
    </main>
  </div>
</div>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script
        src="http://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
        crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="{{ url_for('static', filename='jquery-slim.min.js') }}"><\/script>')</script>
<script src="{{ url_for('static', filename='bootstrap.bundle.min.js') }}"></script>

<!-- Typeahead JS -->
<script src="{{ url_for('static', filename='typeahead.bundle.js') }}"></script>

<!-- Bootstrap Notify JS -->
<script src="{{ url_for('static', filename='bootstrap-notify.js') }}"></script>
<script>
    $.notifyDefaults({
        placement: {
            from: "bottom",
            align: "right"
        },
        delay: 0,
    });
</script>

<!-- Icons -->
<script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
<script>
    feather.replace()
</script>

<script>
    // Bloodhound with Remote + Prefetch
    var object_suggestions = new Bloodhound({
        datumTokenizer: Bloodhound.tokenizers.obj.whitespace('objectid'),
        queryTokenizer: Bloodhound.tokenizers.whitespace,
        remote: {
            url: 'http://localhost:5000/search/%QUERY',
            wildcard: '%QUERY'                    // %QUERY will be replace by users input in
        },                                        // the url option.
    });

    // init Typeahead
    $('input.twitter-typeahead').typeahead(
        {
            minLength: 1,
            highlight: true
        },
        {
            name: 'objects',
            source: object_suggestions,   // suggestion engine is passed as the source
            display: function(item) {        // display: 'name' will also work
                return item.objectid;
            },
            limit: 8,
            templates: {
                suggestion: function(item) {
                    return '<div>'+ item.objectid + '_' + item.revision + ' (' + item.maturity +')</div>';
                }
            }
        }).on('typeahead:selected', function(e, datum) {
            console.log('selected: ' + datum);
        });

</script>

{% from "macro.html" import flashed_messages %}
{%- with messages = get_flashed_messages(with_categories=True) %}
    {{flashed_messages(messages)}}
{%- endwith %}

{% block extrascripts %}
{% endblock %}

</body>
</html>

netmanager_web/templates/macro.html
{% macro render_pagination(pagination) %}
<nav aria-label="Page Navigation">
    <ul class="pagination">
    {%- for page in pagination.iter_pages() %}
        {% if page %}
            {% if page != pagination.page %}
                <li class="page-item"><a class="page-link" href="{{ url_for_other_page(page) }}">{{ page }}</a></li>
            {% else %}
                <li class="page-item active">
                    <a class="page-link" href="{{ url_for_other_page(page) }}">{{ page }} <span class="sr-only">(current)</span></a>
                </li>
            {% endif %}
        {% else %}
            <li class="page-item disabled"><span class=ellipsis>…</span></li>
        {% endif %}
    {%- endfor %}
    {% if pagination.has_next %}
        <li class="page-item"><a class="page-link" href="{{ url_for_other_page(pagination.page + 1) }}#">Next</a></li>
    {% endif %}
    </ul>
</nav>
{% endmacro %}


{% macro flashed_messages(messages=None, transform={
  'critical': { 'type': 'danger',  'icon': 'fa-exclamation-circle'   },
  'error':    { 'type': 'danger',  'icon': 'fa-exclamation-circle'   },
  'info':     { 'type': 'info',    'icon': 'fa-info-circle'          },
  'warning':  { 'type': 'warning', 'icon': 'fa-exclamation-triangle' },
  'debug':    { 'type': 'info',    'icon': 'fa-info-circle'          },
  'notset':   { 'type': 'succes',  'icon': 'fa-check-circle'         },
  'message':  { 'type': 'succes',  'icon': 'fa-check-circle'         },
}, default_category='info') -%}
    {% with messages = messages or get_flashed_messages(with_categories=True) -%}
        {% if messages -%} {# don't output anything if there are no messages #}
        {% for cat, msg in messages %}
    <script>
        $.notify({
            icon: 'fas {{transform.get(cat.lower(), default_category or cat).get('icon')}} mr-1',
            message: '{{ msg }}',
        },{
            type: '{{transform.get(cat.lower(), default_category or cat).get('type')}}',
        });
    </script>
        {%- endfor -%}
        {% endif -%}
    {% endwith -%}
{% endmacro -%}


{% macro icon(type=None, extra_classes=[]) -%}
    <span{{ ({'class': (['glyphicon', 'glyphicon-' + type] + extra_classes)|join(' ')})|xmlattr}}{{kwargs|xmlattr}}></span>
{%- endmacro %}